In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/House Price Prediction Dataset.csv")
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119


In [ ]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056


In [ ]:
# LOGESTIC REGRESSION IMPLEMENTATION

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Id         2000 non-null   int64 
 1   Area       2000 non-null   int64 
 2   Bedrooms   2000 non-null   int64 
 3   Bathrooms  2000 non-null   int64 
 4   Floors     2000 non-null   int64 
 5   YearBuilt  2000 non-null   int64 
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64 
dtypes: int64(7), object(3)
memory usage: 156.4+ KB


In [ ]:
# LABEL ENCODING
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Location"] = le.fit_transform(df["Location"])
df["Condition"] = le.fit_transform(df["Condition"])
df["Garage"] = le.fit_transform(df["Garage"])
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,0,0,149919
1,2,4272,5,4,3,1958,0,0,0,424998
2,3,3592,2,2,3,1938,0,2,0,266746
3,4,966,4,2,2,1902,2,1,1,244020
4,5,4926,1,4,2,1975,0,1,1,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,2,3,0,295620
1996,1997,3046,5,2,1,2019,2,3,1,580929
1997,1998,1062,5,1,2,1903,1,3,0,476925
1998,1999,4062,3,1,2,1936,3,0,1,161119


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop("Price", axis=1), df["Price"], test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([ 60002, 240732, 912303, 498636,  60712, 661473, 297145, 526154,
       643167, 637270, 527032,  53052, 134335, 518239, 890172, 271775,
       328606, 802744, 289317, 420283, 788497, 747143, 161119,  68909,
       387540, 958521,  66040, 182335, 917784, 340375, 752726, 836157,
       201958, 497564, 975168, 490187, 465660, 620569, 910352, 726894,
       919914, 527698, 726894, 635009, 443920, 323010, 730516, 959222,
       976920, 977070, 121074, 393782, 417057, 893382, 374888, 476228,
       232394, 441731, 141257, 423587, 146453, 497695, 133984, 511365,
       929753, 577800, 967899, 926122, 540339, 543301, 874254, 882044,
        52024, 336640, 847399, 545283, 348009,  63672, 240732, 777591,
       593344, 650988, 913624, 875613, 137745, 458449, 506356, 857032,
       982478, 176951, 682592, 354431, 690102, 297439, 265196, 169095,
       213394, 133805, 913624, 295620, 395123, 959222, 490187, 739834,
       695115, 959222,  55310,  79756, 136755, 810135, 920181, 983332,
      

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# TRAIN TEST SPLIT (TARGET IS 'PRICE AS A CATEGORY)
X = df.drop("Price", axis=1)
y = df["Price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# MODEL SELECTION (LOGISTIC REGRESSION)
model = LogisticRegression()
model.fit(X_train, y_train)

# MODEL EVALUATION
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
print("\nConfusion Matrix:")
# The original comment mentioned LinearRegression, but using LogisticRegression here.
# If y_pred from LogisticRegression are class labels, np.round might be redundant.
# If 'Price' is truly continuous, confusion matrix and accuracy are not appropriate.
# For now, following the original code's quantization approach.
y_pred_quantized = np.round(y_pred)
print("Confusion Matrix (Quantized Predictions):")
print(confusion_matrix(y_test, y_pred_quantized))


Accuracy: 0.0

Confusion Matrix:
Confusion Matrix (Quantized Predictions):
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
#performance check krne ke liye
print("Mean Absolute Error", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error", np.sqrt(mean_squared_error(y_test, y_pred)))

In [ ]:
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,0,0,149919
1,2,4272,5,4,3,1958,0,0,0,424998
2,3,3592,2,2,3,1938,0,2,0,266746
3,4,966,4,2,2,1902,2,1,1,244020
4,5,4926,1,4,2,1975,0,1,1,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,2,3,0,295620
1996,1997,3046,5,2,1,2019,2,3,1,580929
1997,1998,1062,5,1,2,1903,1,3,0,476925
1998,1999,4062,3,1,2,1936,3,0,1,161119


In [ ]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [ ]:
!git branch

In [ ]:
!git checkout -b main

Switched to a new branch 'main'


In [ ]:
!git remote add origin
https://github.com/umerabiya966-jpg/house-hold-project.git

SyntaxError: invalid syntax (3324639920.py, line 2)

In [ ]:
!git add  .
!git commit -m "first upload from colab"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@30a2ccac47a4.(none)')


In [ ]:
!git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'origin'


In [ ]:
!git push -u origin master

error: src refspec master does not match any
error: failed to push some refs to 'origin'


In [ ]:
! git init && git checkout -b main

Reinitialized existing Git repository in /content/.git/
Switched to a new branch 'main'


In [ ]:
!git config -- global  user .email "umerabiya966@gmail.com"
!git config -- global user .name "rabia"

usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-pattern]
    --get-all             get all values: key [value-pattern]
    --get-regexp          get values for regexp: name-regex [value-pattern]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value-pattern]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-pattern]
    --unset-all           remove all matches: name [value-pattern]
    --rename-section      rename section: old-name new-name
    --remove-secti

In [ ]:
!1s

/bin/bash: line 1: 1s: command not found


In [ ]:
!git add
!git commit -m "first commit"

Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Turn this message off by running
hint: "git config advice.addEmptyPathspec false"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@30a2ccac47a4.(none)')


In [ ]:
!git remote -v

In [ ]:
!git remote add originhttps://github.com/umerabiya966-jpg/house-hold-project.git

usage: git remote add [<options>] <name> <url>

    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=(push|fetch)]
                          set up remote as a mirror to push to or fetch from



In [ ]:
! git push -u orign main

error: src refspec main does not match any
error: failed to push some refs to 'orign'


In [ ]:
! git remote remove origin

error: No such remote: 'origin'


In [ ]:
!git remote add origin https://github.com/umerabiya966-jpg/house-hold-project.git

error: remote origin already exists.


In [ ]:
!git remote -v

origin	https://github.com/umerabiya966-jpg/house-hold-project.git (fetch)
origin	https://github.com/umerabiya966-jpg/house-hold-project.git (push)


In [ ]:
!git branch

In [ ]:
!git checkout -b main

Switched to a new branch 'main'


In [ ]:
!git add  .
!git commit -m "first commit"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@30a2ccac47a4.(none)')


In [ ]:
!git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/umerabiya966-jpg/house-hold-project.git'


In [ ]:
!git config -- global user.email "umerabiya966@gmail.com"
!git config -- global user.name "Ume Rabia"

error: key does not contain a section: global
error: key does not contain a section: global


In [ ]:
!git config -- global user.email "umerabiya966@gmail.com"
!git config -- global user.name "Ume Rabia"
!git add  .config/
!git commit -m  "first commit"
!git push -u origin main

error: key does not contain a section: global
error: key does not contain a section: global
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@30a2ccac47a4.(none)')
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/umerabiya966-jpg/house-hold-project.git'


In [ ]:
!git add .

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git commit -m"first commit"

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git remote add origin http://github.com/umerabiya966-jpg/supervised-machine-learning.git

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!gitbpush -u origin main!

/bin/bash: line 1: gitbpush: command not found
